I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 5, in script
    if errleen_met == False:
  File "game/script.rpy", line 5, in <module>
    if errleen_met == False:
NameError: name 'errleen_met' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 5, in script
    if errleen_met == False:
  File "/Users/mbrickn/Desktop/renpy-6.99.14.1-sdk/renpy/ast.py", line 1702, in execute
    if renpy.python.py_eval(condition):
  File "/Users/mbrickn/Desktop/renpy-6.99.14.1-sdk/renpy/python.py", line 1843, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/mbrickn/Desktop/renpy-6.99.14.1-sdk/renpy/python.py", line 1836, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 5, in <module>
    if errleen_met == False:
NameError: name 'errleen_met' is not defined

Darwin-16.5.0-x86_64-i386-64bit
Ren'Py 6.99.14.1.3218
DBVN-Easy 1.0
Mon Feb  5 14:49:26 2018
